### ISSUE TITLE
Pocketmine

### ISSUE THREAD

**Issue by callumrawlinson** [Vernox-MC/OPList#1]
Hello!

i have made a version of this for pocketmine that was released 15 days prior to this java version.It would be cool if you could maybe add me to the readme for the pocketmine version!

it is available at https://github.com/callumrawlinson/OP-LIST

**Comment by Vernox-MC** [comment]
Hi! Basically I noticed your OPList was created 20 days ago, however I couldn't help myself noticing that it's a copy and paste from the repository that Dolmation created 2 months ago. Now I'm friends with dolmation so could you give him the credit?

**Comment by callumrawlinson** [comment]
Wait what... it was privated for over 3 months

**Comment by callumrawlinson** [comment]
if necesary i could say he inspired me if you wanted as mine say who is online aswell using a different plugin i have

**Comment by Vernox-MC** [comment]
I mean it's completely copy and pasted lol, I'll direct people to dolmations oplist, thank you and have a good day.

**Comment by callumrawlinson** [comment]
ok! i will add him as credit and update it to show online playerss
