### ISSUE TITLE
Updated my plugin and added collaborators

### ISSUE THREAD

**Issue by callumrawlinson** [Vernox-MC/OPList#2]
Hello sorry for this mistake, the plugin i uploaded was his and not my edited one.i will add him as credit now

**Comment by callumrawlinson** [comment]
my edited one has been added now

**Comment by Vernox-MC** [comment]
Thank you!

**Comment by callumrawlinson** [comment]
Im completly sorry and didnt realise. also if you need any help with anything just ask

**Comment by callumrawlinson** [comment]
@Vernox-MC i need some help with a plugin. is there anywhere i can contact you
